"""adding meetings table and table object  friend_meetings

Revision ID: 89e4418cd6d2
Revises: 8b3df95c41fe
Create Date: 2024-06-10 22:05:58.376984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89e4418cd6d2'
down_revision = '8b3df95c41fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('scheduled_time', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friend_meetings',
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['friends.id'], name=op.f('fk_friend_meetings_friend_id_friends')),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_friend_meetings_meeting_id_meetings')),
    sa.PrimaryKeyConstraint('friend_id', 'meeting_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friend_meetings')
    op.drop_table('meetings')
    # ### end Alembic commands ###
