"""updated schema

Revision ID: 994766710a18
Revises: 2ec69053277e
Create Date: 2024-05-12 15:14:32.503828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '994766710a18'
down_revision = '2ec69053277e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
